### PR TITLE
Chris working area

### PR DESCRIPTION
**Pull request by cvennel**
Moved transaction queue and blockchain out of data storage module (though now that seems unnecessary and empty... maybe some overall directory restructuring is in order).

Added tests and methods for storing blockchain to text file in json

### CODE REVIEW

**Comment by cvennel** [comment]
#37 #17

**Comment by cvennel** [comment]
> Tagging #37 #17. Is that all I have to do?

@Romulus10  is that all I need to do to tag?

**Comment by Romulus10** [comment]
> > Tagging #37 #17. Is that all I have to do?
> 
> @Romulus10 is that all I need to do to tag?

Yeah, that'll link the issue.

**Comment by cvennel** [comment]
@Romulus10  I don't think tagging them worked :/ I moved them around before noticing the tag feature so I may have broken that. oops

**Pull request merged**
